name: fal_client
description: >
  The Dart client library for fal.ai model APIs.
  You can use it to call multiple AI models on your Dart and Flutter apps.
version: 0.2.0
homepage: https://fal.ai
topics:
  - ai
  - fal
  - stable-diffusion
  - sdxl
  - text-to-image

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cross_file: ^0.3.3+6
  http: ^1.1.0
  platform: ^3.1.3

dev_dependencies:
