name: fal_client
description: A client library for fal.ai ML APIs
version: 0.1.0
homepage: https://fal.ai
topics:
  - ai
  - fal
  - stable-diffusion
  - sdxl
  - text-to-image

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cross_file: ^0.3.3+6
  http: ^1.1.0
  platform: ^3.1.3

dev_dependencies:
