
name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: dart pub get
      
      - name: Check format
        run: dart format --set-exit-if-changed lib/

      - name: Analyze code
        run: dart analyze lib/

      - name: Build example app
        run: |
          cd example/
          flutter build web --release
